/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Dao.BookDao;
import Dao.BorrowDao;
import DAO.MemberDao;
import DAO.UserDao;

public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    private int userId;
    private String role;
    
    private BookDao bookDao;
    private MemberDao memberDao;
    private UserDao userDao;
    private BorrowDao borrowDao;
   
    public AdminDashboard(int userId, String role) {
        
        this.userId = userId;
        this.role = role;
        initComponents();
        this.setTitle("Admin Dashboard");
        this.setResizable(false);
        
         bookDao = new BookDao();
        memberDao = new MemberDao();
        userDao = new UserDao();
        borrowDao = new BorrowDao();
        
         loadDashboardStatistics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        totalduebooktxt = new javax.swing.JLabel();
        totalbooktxt = new javax.swing.JLabel();
        totalmembertxt = new javax.swing.JLabel();
        totaluserstxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        recordbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("SINDATHRIYA DIVISION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 330, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 420, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 179, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Manage Users");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 200, 110));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Manage Books");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, 110));

        logoutbtn.setBackground(new java.awt.Color(0, 204, 204));
        logoutbtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(0, 0, 102));
        logoutbtn.setText("Log Out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 110));

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Manage Members");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 200, 110));

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 102));
        jButton6.setText("Manage Borrowings");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 200, 110));

        totalduebooktxt.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        totalduebooktxt.setForeground(new java.awt.Color(0, 0, 102));
        totalduebooktxt.setText("0");
        getContentPane().add(totalduebooktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 140, 60));

        totalbooktxt.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        totalbooktxt.setForeground(new java.awt.Color(0, 0, 102));
        totalbooktxt.setText("0");
        getContentPane().add(totalbooktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, 60));

        totalmembertxt.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        totalmembertxt.setForeground(new java.awt.Color(0, 0, 102));
        totalmembertxt.setText("0");
        getContentPane().add(totalmembertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 130, 60));

        totaluserstxt.setFont(new java.awt.Font("Microsoft YaHei", 1, 48)); // NOI18N
        totaluserstxt.setForeground(new java.awt.Color(0, 0, 102));
        totaluserstxt.setText("0");
        getContentPane().add(totaluserstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 130, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Total Due Books");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Total Books");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("Total Members");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Total Users");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 600));

        recordbtn1.setBackground(new java.awt.Color(0, 204, 204));
        recordbtn1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        recordbtn1.setForeground(new java.awt.Color(0, 0, 102));
        recordbtn1.setText("Records");
        recordbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(recordbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 200, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new UserForm().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new BookForm().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new MemberForm().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new BorrowForm().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void recordbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtn1ActionPerformed
       new RecordsForm().setVisible(true);
    }//GEN-LAST:event_recordbtn1ActionPerformed

   private void loadDashboardStatistics() {
        try {
            int totalBooks = bookDao.getTotalBooksCount();
            totalbooktxt.setText(String.valueOf(totalBooks));
            
            int totalMembers = memberDao.getTotalMembersCount();
            totalmembertxt.setText(String.valueOf(totalMembers));
            
            int totalUsers = userDao.getTotalUsersCount();
            totaluserstxt.setText(String.valueOf(totalUsers));
            
            int totalDueBooks = borrowDao.getTotalDueBooksCount();
            totalduebooktxt.setText(String.valueOf(totalDueBooks));
            
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading dashboard statistics", e);
            totalbooktxt.setText("0");
            totalmembertxt.setText("0");
            totaluserstxt.setText("0");
            totalduebooktxt.setText("0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard(1, "admin").setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton recordbtn1;
    private javax.swing.JLabel totalbooktxt;
    private javax.swing.JLabel totalduebooktxt;
    private javax.swing.JLabel totalmembertxt;
    private javax.swing.JLabel totaluserstxt;
    // End of variables declaration//GEN-END:variables
}
